#!/usr/bin/env python
#
'''
## License
# https://gopigo.io
# https://modrobotics.com
#
# Copyright (c) 2022 Modular Robotics
# Released under the MIT license (http://choosealicense.com/licenses/mit/).
# For more information see https://github.com/DexterInd/DI_Sensors/blob/master/LICENSE.md
'''

'''
THIS IS A COPY OF THE FILE FOUND IN RASPBIAN FOR ROBOTS
DO NOT EDIT THIS FILE
IF CHANGES ARE NEEDED EDIT THE ONE IN RfR THEN PULL IT HERE
-Nicole
'''
import setuptools
setuptools.setup(
	name="Robot_AutoDetection_and_I2C_Mutex",
	version = "1.3.3",
	description="Modular Robotics Robot Autodetection and I2C Mutex Security",
	author="Modular Robotics",
	url="https://GoPiGo.io/",
	py_modules=['auto_detect_robot', 'auto_detect_rpi', 'I2C_mutex', 'di_i2c', 'di_mutex'],
	install_requires=['smbus-cffi', 'pyserial', 'python-periphery', 'wiringpi'],
)
