#!/usr/bin/env python
#
'''
## License
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/gpl-3.0.txt>.
'''
'''
THIS IS A COPY OF THE FILE FOUND IN RASPBIAN FOR ROBOTS
DO NOT EDIT THIS FILE
IF CHANGES ARE NEEDED EDIT THE ONE IN RfR THEN PULL IT HERE
-Nicole
'''
import setuptools
setuptools.setup(
	name="Dexter_AutoDetection_and_I2C_Mutex",
	description="Dexter Industries Robot Autodetection and I2C Mutex Security",
	author="Dexter Industries",
	url="http://www.dexterindustries.com/GoPiGo/",
	py_modules=['auto_detect_robot', 'auto_detect_rpi', 'I2C_mutex'],
	install_requires=['smbus-cffi', 'pyserial'],
)
